package net.moli9ma.boilerplates;

public class RoadBike {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column road_bike.id
     *
     * @mbggenerated Sat Oct 29 20:41:31 JST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column road_bike.name
     *
     * @mbggenerated Sat Oct 29 20:41:31 JST 2016
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column road_bike.id
     *
     * @return the value of road_bike.id
     *
     * @mbggenerated Sat Oct 29 20:41:31 JST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column road_bike.id
     *
     * @param id the value for road_bike.id
     *
     * @mbggenerated Sat Oct 29 20:41:31 JST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column road_bike.name
     *
     * @return the value of road_bike.name
     *
     * @mbggenerated Sat Oct 29 20:41:31 JST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column road_bike.name
     *
     * @param name the value for road_bike.name
     *
     * @mbggenerated Sat Oct 29 20:41:31 JST 2016
     */
    public void setName(String name) {
        this.name = name;
    }
}